### ISSUE TITLE
Color Wheel

### ISSUE THREAD

**Issue by matrix4767** [hako-mikan/sd-webui-cd-tuner#11]
Is it possible to add some sort of color wheel to help adjust colors for the color map tab?

**Comment by hako-mikan** [comment]
It's difficult to add Color Wheel dew to Gradio
Instead of Color Wheel, I added color preset dropdown which can add colors easily.

**Comment by sandner-art** [comment]
I get this:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 293: character maps to <undefined>

Full error:

*** Error loading script: cdtuner.py
    Traceback (most recent call last):
      File "C:\SDXL\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\SDXL\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\SDXL\stable-diffusion-webui\extensions\sd-webui-cd-tuner\scripts\cdtuner.py", line 22, in <module>
        ui_config = json.load(json_file)
      File "C:\Users\quant\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
        return loads(fp.read(),
      File "C:\Users\quant\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 293: character maps to <undefined>

---

**Comment by hako-mikan** [comment]
maybe fixed.
