### ISSUE TITLE
Not working on Automatic1111

### ISSUE THREAD

**Issue by asopasopaso** [hako-mikan/sd-webui-cd-tuner#34]
いつもお世話になっています。
Forge対応ありがとうございました。非常に助かっています。
一方、Automatic1111で正常に機能しなくなっているようです。

> *** Error running process_batch: C:\stable-diffusion-webui\extensions\sd-webui-cd-tuner\scripts\cdtuner.py
>     Traceback (most recent call last):
>       File "C:\stable-diffusion-webui\modules\scripts.py", line 864, in process_batch
>         script.process_batch(p, *script_args, **kwargs)
>       File "C:\stable-diffusion-webui\extensions\sd-webui-cd-tuner\scripts\cdtuner.py", line 328, in process_batch
>         vaedealer2(self)
>       File "C:\stable-diffusion-webui\extensions\sd-webui-cd-tuner\scripts\cdtuner.py", line 462, in vaedealer2
>         self.storedweights_vae2[name] = getset_nested_module_tensor(True, shared.sd_model, name).clone()
>       File "C:\stable-diffusion-webui\extensions\sd-webui-cd-tuner\scripts\cdtuner.py", line 491, in getset_nested_module_tensor
>         target_module = getattr(target_module, module_name)
>       File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
>         raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
>     AttributeError: 'DiffusionEngine' object has no attribute 'forge_objects_after_applying_lora'

**Comment by webmadmangit** [comment]
Getting the same error.

**Comment by kuschanow** [comment]
The same for me

**Comment by webmadmangit** [comment]
Works for me. Thanks!
